# YAML file for configuration and paths of the data processor

# Region Selection is done via the official US Census Bureau FIPS codes
# An overview can be found here: https://www2.census.gov/geo/docs/reference/codes/files/national_cousub.txt
# states: MA = Massachusetts, AL = Alabama, CA = California, etc.
# counties: Autauga County, 003 = Baldwin County, etc.
# count_subdivisions: Autaugaville CCD,
region:
  state: "MA" # Valid abbreviation
  county: "Middlesex County" # Required
  county_subdivision: "Cambridge city" # optional, if not provided, all subdivisions will be downloaded
  lookup_url: https://www2.census.gov/geo/docs/reference/codes/files/national_cousub.txt

# Base output directory
output_dir: "syngrid/data_processor/output/"  
  
input_data:

  # Census data paths
  census_population: "ZensusPopulation/ZensusPopulation.shp"
  census_buildings: "ZensusGebaude/ZensusGebaude.shp"
  
  # Geofabrik data paths
  geofabrik_buildings: "GeoFabrik_Buildings/gis_osm_buildings_a_free_1.shp"
  geofabrik_pois: "GeoFabrik_Points/gis_osm_pois_a_free_1.shp"
  geofabrik_landuse: "GeoFabrik_Landuse/gis_osm_landuse_a_free_1.shp"
  
  # NLCD landuse data path
  nlcd_landuse: "NLCD_Landuse/NLCD_Landuse.shp"

# Overpass API configuration
overpass:
  api_url: "http://overpass-api.de/api/interpreter"
  timeout: 500  # Timeout in seconds

# Processing parameters
processing:
  distance_threshold_meters: 10  # Distance threshold for deduplication
  crs: "epsg:4326"  # Coordinate reference system

# API keys
api_keys:
  census_api_key: ""  # Replace with your actual API key
